import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  LOG_LEVEL: Joi.string().valid('fatal', 'error', 'warn', 'info', 'debug', 'trace', 'silent').optional(),
  DATABASE_URL: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_EXPIRES_IN: Joi.string().default('1h'),
  REFRESH_TOKEN_SECRET: Joi.string().required(),
  REFRESH_TOKEN_EXPIRES_IN: Joi.string().default('7d'),
  SMTP_HOST: Joi.string().optional(),
  SMTP_PORT: Joi.number().optional(),
  SMTP_USER: Joi.string().optional(),
  SMTP_PASSWORD: Joi.string().optional(),
  EMAIL_FROM: Joi.string().optional(),
  CLOUDINARY_CLOUD_NAME: Joi.string().optional(),
  CLOUDINARY_API_KEY: Joi.string().optional(),
  CLOUDINARY_API_SECRET: Joi.string().optional(),
  STELLAR_NETWORK: Joi.string().valid('testnet', 'mainnet').default('testnet'),
  STELLAR_RPC_URL: Joi.string().uri().optional(),
  STELLAR_RPC_TIMEOUT_MS: Joi.number().integer().positive().default(10000),
  STELLAR_RPC_MAX_RETRIES: Joi.number().integer().min(0).max(10).default(3),
  STELLAR_RPC_RETRY_BASE_DELAY_MS: Joi.number().integer().positive().default(200),
  WORKSPACE_BOOKING_CONTRACT_ID: Joi.string().optional(),
  MEMBERSHIP_TOKEN_CONTRACT_ID: Joi.string().optional(),
  FRONTEND_URL: Joi.string().default('http://localhost:3000'),
  REDIS_URL: Joi.string().optional(),
  HIBP_CHECK_ENABLED: Joi.boolean().default(false),
  MAX_SESSION_HOURS: Joi.number().default(12),
});
